#!/usr/bin/env python3
"""Seed 20 test properties in Oberá — mirrors InmuebleBot's seed_obera.py."""

import asyncio
import sys
from pathlib import Path

# Add project root to path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from sqlalchemy import select
from app.core.database import async_session
from app.models.property import Property

SEED_PROPERTIES = [
    # === CENTRO — Alquiler ===
    {
        "title": "Depto 2 ambientes céntrico",
        "operation": "alquiler",
        "property_type": "departamento",
        "zone": "Centro",
        "city": "Oberá",
        "price": 85000,
        "bedrooms": 1,
        "bathrooms": 1,
        "covered_m2": 45,
        "total_m2": 50,
        "description": "Hermoso departamento de 2 ambientes en pleno centro. Living-comedor, cocina, 1 dormitorio, baño completo. A estrenar. Ideal profesional.",
        "address": "Córdoba 450, Centro, Oberá",
        "images": ["centro_depto1_01.jpg", "centro_depto1_02.jpg", "centro_depto1_03.jpg"],
        "amenities": ["agua_corriente", "gas_natural", "internet"],
    },
    {
        "title": "Depto 3 ambientes con balcón",
        "operation": "alquiler",
        "property_type": "departamento",
        "zone": "Centro",
        "city": "Oberá",
        "price": 120000,
        "bedrooms": 2,
        "bathrooms": 1,
        "covered_m2": 65,
        "total_m2": 70,
        "description": "Departamento de 3 ambientes con balcón a la calle. Dos dormitorios, living amplio, cocina-comedor. Excelente ubicación a metros de la plaza central.",
        "address": "San Martín 820, Centro, Oberá",
        "images": ["centro_depto2_01.jpg", "centro_depto2_02.jpg"],
        "amenities": ["agua_corriente", "gas_natural", "balcon", "lavadero"],
    },
    {
        "title": "Monoambiente Centro económico",
        "operation": "alquiler",
        "property_type": "departamento",
        "zone": "Centro",
        "city": "Oberá",
        "price": 55000,
        "bedrooms": 0,
        "bathrooms": 1,
        "covered_m2": 30,
        "total_m2": 30,
        "description": "Monoambiente económico en el centro. Ideal estudiante. Cocina integrada, baño privado. Todo electricidad.",
        "address": "Jujuy 320, Centro, Oberá",
        "images": ["centro_mono_01.jpg"],
        "amenities": ["electricidad", "internet"],
    },
    # === CENTRO — Venta ===
    {
        "title": "Casa 3 dormitorios Centro",
        "operation": "venta",
        "property_type": "casa",
        "zone": "Centro",
        "city": "Oberá",
        "price": 45000000,
        "bedrooms": 3,
        "bathrooms": 2,
        "covered_m2": 120,
        "total_m2": 200,
        "description": "Casa familiar en el centro con 3 dormitorios, 2 baños, living-comedor, cocina, lavadero y garaje para 2 autos. Excelente estado. Patio amplio con parrilla.",
        "address": "Belgrano 640, Centro, Oberá",
        "images": ["centro_casa1_01.jpg", "centro_casa1_02.jpg", "centro_casa1_03.jpg", "centro_casa1_04.jpg"],
        "amenities": ["agua_corriente", "gas_natural", "garaje", "parrilla", "patio"],
    },
    {
        "title": "Depto 2 ambientes a estrenar",
        "operation": "venta",
        "property_type": "departamento",
        "zone": "Centro",
        "city": "Oberá",
        "price": 35000000,
        "bedrooms": 1,
        "bathrooms": 1,
        "covered_m2": 48,
        "total_m2": 52,
        "description": "Departamento a estrenar en edificio nuevo. Living-cocina integrado, dormitorio con placard, baño completo. Cochera cubierta opcional.",
        "address": "Sarmiento 1230, Centro, Oberá",
        "images": ["centro_depto3_01.jpg", "centro_depto3_02.jpg"],
        "amenities": ["agua_corriente", "gas_natural", "cochera_opcional", "edificio_nuevo"],
    },
    # === UNAM — Alquiler ===
    {
        "title": "Depto estudiante cerca UNAM",
        "operation": "alquiler",
        "property_type": "departamento",
        "zone": "UNAM",
        "city": "Oberá",
        "price": 60000,
        "bedrooms": 1,
        "bathrooms": 1,
        "covered_m2": 35,
        "total_m2": 38,
        "description": "Departamento ideal estudiantes a 3 cuadras de la UNAM. Un dormitorio, cocina-comedor, baño. Tranquilo, luminoso.",
        "address": "Misiones 980, Zona UNAM, Oberá",
        "images": ["unam_depto1_01.jpg"],
        "amenities": ["electricidad", "internet", "cerca_unam"],
    },
    {
        "title": "Casa compartida estudiantes UNAM",
        "operation": "alquiler",
        "property_type": "casa",
        "zone": "UNAM",
        "city": "Oberá",
        "price": 45000,
        "bedrooms": 4,
        "bathrooms": 2,
        "covered_m2": 100,
        "total_m2": 150,
        "description": "Casa grande ideal para compartir entre estudiantes. 4 habitaciones individuales, 2 baños, cocina equipada, living, patio. A 5 cuadras de la UNAM.",
        "address": "Corrientes 2150, Zona UNAM, Oberá",
        "images": ["unam_casa1_01.jpg", "unam_casa1_02.jpg"],
        "amenities": ["agua_corriente", "gas_natural", "patio", "cerca_unam", "cocina_equipada"],
    },
    {
        "title": "Monoambiente UNAM económico",
        "operation": "alquiler",
        "property_type": "departamento",
        "zone": "UNAM",
        "city": "Oberá",
        "price": 40000,
        "bedrooms": 0,
        "bathrooms": 1,
        "covered_m2": 25,
        "total_m2": 25,
        "description": "Monoambiente económico a 2 cuadras de la UNAM. Ideal estudiante soltero. Baño privado, cocina eléctrica.",
        "address": "Av. Libertad 1780, Zona UNAM, Oberá",
        "images": ["unam_mono_01.jpg"],
        "amenities": ["electricidad", "cerca_unam"],
    },
    # === BARRIO SCHUSTER ===
    {
        "title": "Casa 2 dormitorios Schuster",
        "operation": "alquiler",
        "property_type": "casa",
        "zone": "Barrio Schuster",
        "city": "Oberá",
        "price": 70000,
        "bedrooms": 2,
        "bathrooms": 1,
        "covered_m2": 60,
        "total_m2": 120,
        "description": "Casa en Barrio Schuster con 2 dormitorios, living-comedor, cocina y baño. Terreno grande con árboles frutales. Zona tranquila, familiar.",
        "address": "Los Lapachos 450, Barrio Schuster, Oberá",
        "images": ["schuster_casa1_01.jpg", "schuster_casa1_02.jpg"],
        "amenities": ["agua_corriente", "gas_natural", "arboles_frutales", "terreno_grande"],
    },
    {
        "title": "Casa 3 dormitorios Schuster",
        "operation": "venta",
        "property_type": "casa",
        "zone": "Barrio Schuster",
        "city": "Oberá",
        "price": 28000000,
        "bedrooms": 3,
        "bathrooms": 2,
        "covered_m2": 95,
        "total_m2": 250,
        "description": "Casa familiar en Barrio Schuster. 3 dormitorios, 2 baños, living-comedor con estufa, cocina-amoblada. Galería, garaje, parrilla. Terreno de 250m2 con jardín.",
        "address": "Las Azaleas 720, Barrio Schuster, Oberá",
        "images": ["schuster_casa2_01.jpg", "schuster_casa2_02.jpg", "schuster_casa2_03.jpg"],
        "amenities": ["agua_corriente", "gas_natural", "garaje", "parrilla", "galeria", "jardin"],
    },
    {
        "title": "PH 2 dormitorios Schuster",
        "operation": "alquiler",
        "property_type": "ph",
        "zone": "Barrio Schuster",
        "city": "Oberá",
        "price": 65000,
        "bedrooms": 2,
        "bathrooms": 1,
        "covered_m2": 55,
        "total_m2": 80,
        "description": "PH en Barrio Schuster. 2 dormitorios, living-comedor, cocina separada, baño, patio interno. Muy luminoso. Entrada independiente.",
        "address": "Los Jazmines 340, Barrio Schuster, Oberá",
        "images": ["schuster_ph1_01.jpg"],
        "amenities": ["agua_corriente", "gas_natural", "patio_interno", "entrada_independiente"],
    },
    {
        "title": "Casa Schuster en venta",
        "operation": "venta",
        "property_type": "casa",
        "zone": "Barrio Schuster",
        "city": "Oberá",
        "price": 22000000,
        "bedrooms": 2,
        "bathrooms": 1,
        "covered_m2": 70,
        "total_m2": 180,
        "description": "Casa en venta en Barrio Schuster. 2 dormitorios amplios, baño, cocina-comedor, living. Terreno de 180m2 con galpón. Ideal para ampliar.",
        "address": "Las Orquídeas 150, Barrio Schuster, Oberá",
        "images": ["schuster_casa3_01.jpg", "schuster_casa3_02.jpg"],
        "amenities": ["agua_corriente", "gas_natural", "galpon", "terreno_amplio"],
    },
    # === RUTA 14 ===
    {
        "title": "Terreno sobre Ruta 14",
        "operation": "venta",
        "property_type": "terreno",
        "zone": "Ruta 14",
        "city": "Oberá",
        "price": 8000000,
        "bedrooms": 0,
        "bathrooms": 0,
        "covered_m2": 0,
        "total_m2": 600,
        "description": "Terreno de 600m2 sobre Ruta 14, a 2km del centro. Ideal para comercio, depósito o vivienda. Todos los servicios. Excelente ubicación comercial.",
        "address": "Ruta Nacional 14 km 875, Oberá",
        "images": ["ruta14_terreno1_01.jpg"],
        "amenities": ["agua_corriente", "electricidad", "frente_ruta", "apto_comercio"],
    },
    {
        "title": "Casa quinta Ruta 14",
        "operation": "venta",
        "property_type": "casa",
        "zone": "Ruta 14",
        "city": "Oberá",
        "price": 35000000,
        "bedrooms": 3,
        "bathrooms": 2,
        "covered_m2": 130,
        "total_m2": 1200,
        "description": "Casa quinta sobre Ruta 14 con 3 dormitorios, 2 baños, living con hogar, cocina-comedor, galería. Terreno de 1200m2 con pileta, quincho y monte frutal.",
        "address": "Ruta Nacional 14 km 878, Oberá",
        "images": ["ruta14_quinta1_01.jpg", "ruta14_quinta1_02.jpg", "ruta14_quinta1_03.jpg", "ruta14_quinta1_04.jpg"],
        "amenities": ["agua_corriente", "gas_natural", "pileta", "quincho", "monte_frutal", "galeria"],
    },
    {
        "title": "Depto cerca Ruta 14 y Centro",
        "operation": "alquiler",
        "property_type": "departamento",
        "zone": "Ruta 14",
        "city": "Oberá",
        "price": 75000,
        "bedrooms": 1,
        "bathrooms": 1,
        "covered_m2": 42,
        "total_m2": 45,
        "description": "Departamento a 4 cuadras de Ruta 14, cerca del centro. 1 dormitorio, living-comedor, cocina, baño. Zona de fácil acceso. Colectivo en la puerta.",
        "address": "Av. de las Américas 1100, Zona Ruta 14, Oberá",
        "images": ["ruta14_depto1_01.jpg", "ruta14_depto1_02.jpg"],
        "amenities": ["agua_corriente", "gas_natural", "colectivo", "facil_acceso"],
    },
    {
        "title": "PH económico Ruta 14",
        "operation": "alquiler",
        "property_type": "ph",
        "zone": "Ruta 14",
        "city": "Oberá",
        "price": 50000,
        "bedrooms": 1,
        "bathrooms": 1,
        "covered_m2": 38,
        "total_m2": 50,
        "description": "PH económico cerca de Ruta 14. 1 dormitorio, living-cocina integrado, baño. Patio compartido. Ideal pareja joven. Zona tranquila.",
        "address": "Chacabuco 2340, Zona Ruta 14, Oberá",
        "images": ["ruta14_ph1_01.jpg"],
        "amenities": ["electricidad", "patio_compartido"],
    },
    # === Additional spread across zones ===
    {
        "title": "Terreno Barrio Schuster",
        "operation": "venta",
        "property_type": "terreno",
        "zone": "Barrio Schuster",
        "city": "Oberá",
        "price": 5500000,
        "bedrooms": 0,
        "bathrooms": 0,
        "covered_m2": 0,
        "total_m2": 400,
        "description": "Terreno de 400m2 en Barrio Schuster. Zona residencial tranquila. Todos los servicios. Ideal para construir casa familiar.",
        "address": "Los Cedros s/n, Barrio Schuster, Oberá",
        "images": ["schuster_terreno1_01.jpg"],
        "amenities": ["agua_corriente", "electricidad", "zona_residencial"],
    },
    {
        "title": "Casa 2 dormitorios Centro alquiler",
        "operation": "alquiler",
        "property_type": "casa",
        "zone": "Centro",
        "city": "Oberá",
        "price": 95000,
        "bedrooms": 2,
        "bathrooms": 1,
        "covered_m2": 70,
        "total_m2": 100,
        "description": "Casa en alquiler en el centro. Dos dormitorios, living, cocina-comedor, baño, lavadero y patio. Muy luminosa. A 5 cuadras del hospital.",
        "address": "Entre Ríos 550, Centro, Oberá",
        "images": ["centro_casa2_01.jpg", "centro_casa2_02.jpg"],
        "amenities": ["agua_corriente", "gas_natural", "patio", "lavadero", "cerca_hospital"],
    },
    {
        "title": "Depto 1 dormitorio UNAM zona",
        "operation": "alquiler",
        "property_type": "departamento",
        "zone": "UNAM",
        "city": "Oberá",
        "price": 55000,
        "bedrooms": 1,
        "bathrooms": 1,
        "covered_m2": 38,
        "total_m2": 40,
        "description": "Departamento de 1 dormitorio en zona UNAM. Living-comedor, cocina, baño. Muy luminoso. A pasos de las facultades.",
        "address": "Av. De los Inmigrantes 450, Zona UNAM, Oberá",
        "images": ["unam_depto2_01.jpg", "unam_depto2_02.jpg"],
        "amenities": ["electricidad", "internet", "cerca_unam", "luminoso"],
    },
]


async def seed():
    """Seed the database with 20 Oberá properties if empty."""
    async with async_session() as session:
        result = await session.execute(select(Property).limit(1))
        existing = result.scalars().first()

        if existing:
            print(f"Database already has properties (found: {existing.title}). Skipping seed.")
            return

        for i, data in enumerate(SEED_PROPERTIES, 1):
            prop = Property(**data)
            session.add(prop)
            print(f"  [{i:02d}] {data['title']} | {data['zone']} | ${data['price']:,.0f}")

        await session.commit()
        print(f"\n✅ Seeded {len(SEED_PROPERTIES)} properties in Oberá")


if __name__ == "__main__":
    asyncio.run(seed())
